""" Fibonaccie sequence is generated by addint teh previous two terms
find the value of adding all positive numbers in a fibbonaci squence
less than 4 million"""

#Following is a fibonaci function
def fibseq(numb):
    num, numlast = 1,1
    #line = 0
    for value in range(numb -1):
        num, numlast = numlast,numlast+num
        print num
        summ = 0
        summ += num
     #   line += 1
        print ("The total sum so far is %d " % summ)
      #  print ("The line is %d " % line)
    return num
print fibseq(33)



